PainGuest/PainGuest/Models/GuestDetail.cs
namespace PainGuest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class GuestDetail
    {
        public int id { get; set; }

        [Display(Name = "Guest Name"), Required, StringLength(100)]
        public string GuestName { get; set; }

        [Display(Name = "Gender"), Required]
        public int GuestGenderID { get; set; }

        [Display(Name = "Mobile Number"), Required, MinLength(10, ErrorMessage = "Mobile Number should have 10 Numbers"), MaxLength(10, ErrorMessage = "Mobile Number Cant be more than 10 Number"), DataType(DataType.PhoneNumber)]
        public string GuestMobileNumber { get; set; }


        [Display(Name = "Father Name"), StringLength(100),Required]
        public string GuestFathersName { get; set; }

        [Display(Name = "Date of Birth"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? GuestDateOfBirth { get; set; }

        [Display(Name = "Age"), Range(18, 100), Required]
        public int? GuestAge { get; set; }

        [Display(Name = "Permanent Address"), StringLength(250), Required]
        public string GuestPermanentAddress { get; set; }

        [Display(Name = "Temperory Address"), StringLength(250)]
        public string GuestTemporaryAddress { get; set; }

        [Display(Name = "Email Address"), StringLength(100), RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Enter Valid Email Address")]
        public string GuestMailId { get; set; }

        [Display(Name = "Educational Qualification"), StringLength(100)]
        public string EducationalQualification { get; set; }


        [Display(Name = "Admission Date"), Required, DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DateOfAdmission { get; set; }

        [Display(Name = "Emergency Contact Number"), StringLength(10), MinLength(10), MaxLength(10), Required]
        public string EmergencyContactNumber { get; set; }

        [Display(Name = "Relationship"), StringLength(50), DataType(DataType.Text), Required]
        public string EmergencyContactNumberRelationship { get; set; }

        [Display(Name = "Office Address"), StringLength(250)]
        public string GuestOfficeAddress { get; set; }

        [Display(Name = "Office Phone Number"), StringLength(10)]
        public string Gst_OfficeTelephoneNumber { get; set; }

        [Display(Name = "Monthly Rent"), Required]
        public decimal? MonthlyRent { get; set; }

        [Display(Name = "Advance Amount"), Required]
        public decimal? AdvanceAmount { get; set; }

        //[Display(Name = "Deposit Amount")]
        //public decimal? DepositAmount { get; set; }

        public DateTime? DateCreated { get; set; }
        public DateTime? DateUpdated { get; set; }

        [Display(Name = "Room Type"), Required]
        public int RoomType { get; set; }

        [Display(Name = "Room Number"), Required]
        public int RoomNumber { get; set; }

        [Display(Name = "Bed Number"), Required]
        public int BedNumber { get; set; }
        public string isRoomVacant { get; set; }
    }
}

PainGuest/PainGuest/Models/GuestDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PainGuest.Models
{
    public class GuestDetailsView
    {
        public int id { get; set; }
        [Display(Name = "Guest Name")]
        public string GuestName { get; set; }
        public int? GuestGenderID { get; set; }
        [Display(Name = "Gender")]
        public string GuestGenderName { get; set; }
        [Display(Name = "Mobile Number")]
        public string GuestMobileNumber { get; set; }
        [Display(Name = "Father Name")]
        public string GuestFathersName { get; set; }
        [Display(Name = "Date of Birth")]
        public DateTime? GuestDateOfBirth { get; set; }
        [Display(Name = "Age")]
        public int? GuestAge { get; set; }
        [Display(Name = "Permanent Address")]
        public string GuestPermanentAddress { get; set; }
        [Display(Name = "Temporory address")]
        public string GuestTemporaryAddress { get; set; }
        [Display(Name = "Mail Id")]
        public string GuestMailId { get; set; }
        [Display(Name = "Educational Qualification")]
        public string EducationalQualification { get; set; }
        [Display(Name = "Date of Admission")]
        public DateTime? DateOfAdmission { get; set; }
        [Display(Name = "Emergency Contact Number")]
        public string EmergencyContactNumber { get; set; }
        [Display(Name = "Relationship")]
        public string EmergencyContactNumberRelationship { get; set; }
        [Display(Name = "Office Address")]
        public string GuestOfficeAddress { get; set; }
        [Display(Name = "Telephone Number")]
        public string Gst_OfficeTelephoneNumber { get; set; }
        [Display(Name = "Monthly Rent")]
        public decimal? MonthlyRent { get; set; }

        [Display(Name = "Advance Amount")]
        public decimal? AdvanceAmount { get; set; }
        [Display(Name = "Deposit Amount")]
        public decimal? DepositAmount { get; set; }

        public DateTime? DateCreated { get; set; }
        public int RoomType { get; set; }
        [Display(Name = "Room Type")]
        public string RoomTypeName { get; set; }
        [Display(Name = "Room Number")]
        public int RoomNumber { get; set; }
        [Display(Name = "Bed Number")]
        public int BedNumber { get; set; }
        public string isRoomVacant { get; set; }

    }
}

PainGuest/PainGuest/Controllers/GuestDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PainGuest.Models;
using Rotativa;
using Rotativa.Options;

namespace PainGuest.Controllers
{
    public class GuestDetailsController : Controller
    {
        private ModelMain db = new ModelMain();

        // GET: GuestDetails
        public ActionResult Index()
        {
            var data = (from a in db.GuestDetails
                        join b in db.MasterGenders on a.GuestGenderID equals b.gender_id
                        join c in db.MasterRoomTypes on a.RoomType equals c.RoomTypeID
                        select new GuestDetailsView
                        {
                            id = a.id,
                            GuestName = a.GuestName,
                            GuestFathersName = a.GuestFathersName,
                            GuestGenderName = b.genderName,
                            GuestMobileNumber = a.GuestMobileNumber,
                            GuestMailId = a.GuestMailId,
                            EducationalQualification = a.EducationalQualification,
                            GuestAge = a.GuestAge,
                            GuestDateOfBirth = a.GuestDateOfBirth,
                            GuestPermanentAddress = a.GuestPermanentAddress,
                            GuestTemporaryAddress = a.GuestTemporaryAddress,
                            GuestOfficeAddress = a.GuestOfficeAddress,
                            Gst_OfficeTelephoneNumber = a.Gst_OfficeTelephoneNumber,
                            MonthlyRent = a.MonthlyRent,
                            AdvanceAmount = a.AdvanceAmount,
                            DateOfAdmission = a.DateOfAdmission,
                            EmergencyContactNumber = a.EmergencyContactNumber,
                            EmergencyContactNumberRelationship = a.EmergencyContactNumberRelationship,
                            //DepositAmount = a.DepositAmount,
                            RoomNumber = a.RoomNumber,
                            BedNumber = a.BedNumber,
                            RoomTypeName = c.RoomTypeName
                        });
            return View(data.ToList());
        }

        // GET: GuestDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestDetail guestDetail = db.GuestDetails.Find(id);
            if (guestDetail == null)
            {
                return HttpNotFound();
            }
            return View(guestDetail);
        }
        [HttpGet]
        public ActionResult PrintAdvanceRecept(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestDetail guestDetail = db.GuestDetails.Find(id);
            AdvanceReciptView advanceReciptView = new AdvanceReciptView();
            advanceReciptView.id = guestDetail.id;
            advanceReciptView.GuestName = guestDetail.GuestName;
            advanceReciptView.AdvanceAmount = guestDetail.AdvanceAmount;
            if (advanceReciptView == null)
            {
                return HttpNotFound();
            }
            //return View(advanceReciptView);
            return new PartialViewAsPdf("PrintAdvanceRecept", advanceReciptView)
            {

                PageOrientation = Orientation.Portrait,
                PageSize = Size.B0,
                //CustomSwitches = "--footer-center \" [page] Page of [toPage] Pages\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                FileName = "AdvanceReciept_" + advanceReciptView.GuestName + ".pdf"
            };
        }
        // GET: GuestDetails/Create
        public ActionResult Create()
        {
            GuestDetail guestDetail = new GuestDetail();
            ViewBag.RoomType = new SelectList(db.MasterRoomTypes, "RoomTypeID", "RoomTypeName");
            ViewBag.GuestGenderID = new SelectList(db.MasterGenders, "gender_id", "genderName");
            ViewBag.RoomNumber = new SelectList(db.MasterRooms.Where(x => x.RoomTypeID == guestDetail.RoomType), "RoomNumber", "RoomNumber");
            ViewBag.BedNumber = new SelectList(db.MasterRooms.Where(x => x.RoomTypeID == guestDetail.RoomType).Where(x => x.RoomNumber == guestDetail.RoomNumber), "BedNumber", "BedNumber");
            return View();
        }

        // POST: GuestDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,GuestName,GuestGenderID,GuestMobileNumber,GuestFathersName,GuestDateOfBirth,GuestAge,GuestPermanentAddress,GuestTemporaryAddress,GuestMailId,EducationalQualification,DateOfAdmission,EmergencyContactNumber,EmergencyContactNumberRelationship,GuestOfficeAddress,Gst_OfficeTelephoneNumber,MonthlyRent,AdvanceAmount,RoomType,RoomNumber,BedNumber,isRoomVacant")] GuestDetail guestDetail)
        {
            try
            {
                ViewBag.RoomType = new SelectList(db.MasterRoomTypes, "RoomTypeID", "RoomTypeName", guestDetail.RoomType);
                ViewBag.GuestGenderID = new SelectList(db.MasterGenders, "gender_id", "genderName", guestDetail.GuestGenderID);
                ViewBag.RoomNumber = new SelectList(db.MasterRooms, "RoomNumber", "RoomNumber", guestDetail.RoomNumber);
                ViewBag.BedNumber = new SelectList(db.MasterRooms, "BedNumber", "BedNumber", guestDetail.BedNumber);

                if (guestDetail.RoomType > 0)
                {
                    ViewBag.RoomNumber = new SelectList(db.MasterRooms.Where(x => x.RoomTypeID == guestDetail.RoomType), "RoomNumber", "RoomNumber", guestDetail.RoomNumber);
                    var c = db.MasterRooms.Where(x => x.RoomTypeID == guestDetail.RoomType).Select(x => x.RoomNumber).Distinct().ToList();
                    //ViewBag.RoomNumber = new SelectList(c, "RoomNumber", "RoomNumber", guestDetail.RoomNumber);
                    //bind Room Numbers
                }
                if (guestDetail.RoomNumber > 0)
                {
                    ViewBag.BedNumber = new SelectList(db.MasterRooms.Where(x => x.RoomTypeID == guestDetail.RoomType).Where(x => x.RoomNumber == guestDetail.RoomNumber), "BedNumber", "BedNumber", guestDetail.BedNumber);
                    //bind Bed Numbers
                }
                //Checking Room and Bed Available or Not 
                if (isRoomBedAvailable(guestDetail.RoomNumber, guestDetail.BedNumber))
                {
                    if (ModelState.IsValid)
                    {
                        guestDetail.DateCreated = DateTime.Now;
                        guestDetail.DateUpdated = DateTime.Now;
                        guestDetail.isRoomVacant = "N";
                        db.GuestDetails.Add(guestDetail);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    return View(guestDetail);
                }
                else
                {
                    //Room Not Available;
                    return View();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: GuestDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.RoomType = new SelectList(db.MasterRoomTypes, "RoomTypeID", "RoomTypeName");
            ViewBag.GuestGenderID = new SelectList(db.MasterGenders, "gender_id", "genderName");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestDetail guestDetail = db.GuestDetails.Find(id);
            if (guestDetail == null)
            {
                return HttpNotFound();
            }
            return View(guestDetail);
        }

        // POST: GuestDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,GuestName,GuestGenderID,GuestMobileNumber,GuestFathersName,GuestDateOfBirth,GuestAge,GuestPermanentAddress,GuestTemporaryAddress,GuestMailId,EducationalQualification,DateOfAdmission,EmergencyContactNumber,EmergencyContactNumberRelationship,GuestOfficeAddress,Gst_OfficeTelephoneNumber,MonthlyRent,AdvanceAmount,RoomType,RoomNumber,BedNumber")] GuestDetail guestDetail)
        {
            if (ModelState.IsValid)
            {
                guestDetail.DateUpdated = DateTime.Now;
                guestDetail.isRoomVacant = "N";
                db.Entry(guestDetail).State = EntityState.Modified;
                db.Entry(guestDetail).Property(x => x.DateCreated).IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoomType = new SelectList(db.MasterRoomTypes, "RoomTypeID", "RoomTypeName", guestDetail.RoomType);
            ViewBag.GuestGenderID = new SelectList(db.MasterGenders, "gender_id", "genderName", guestDetail.GuestGenderID);
            return View(guestDetail);
        }

        // GET: GuestDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.RoomType = new SelectList(db.MasterRoomTypes, "RoomTypeID", "RoomTypeName");
            ViewBag.GuestGenderID = new SelectList(db.MasterGenders, "gender_id", "genderName");
            if (id == null)

PainGuest/PainGuest/Views/GuestDetails/Create.cshtml
@model PainGuest.Models.GuestDetail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>GuestDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GuestName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestGenderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GuestGenderID", null, "Select Gender", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GuestGenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestMobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestMobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestMobileNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestFathersName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestFathersName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestFathersName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestDateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestDateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestDateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestPermanentAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestPermanentAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestPermanentAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestTemporaryAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestTemporaryAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestTemporaryAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestMailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestMailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestMailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EducationalQualification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EducationalQualification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EducationalQualification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfAdmission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfAdmission, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfAdmission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactNumberRelationship, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactNumberRelationship, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactNumberRelationship, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GuestOfficeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestOfficeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestOfficeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gst_OfficeTelephoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gst_OfficeTelephoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gst_OfficeTelephoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MonthlyRent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MonthlyRent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MonthlyRent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdvanceAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdvanceAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdvanceAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.DepositAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DepositAmount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DepositAmount, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.RoomType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoomType", null, "Select Room Type", htmlAttributes: new { @class = "form-control", @onchange = "this.form.submit();" })
                @* @Html.EditorFor(model => model.RoomType, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.RoomType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("RoomNumber", (SelectList)ViewBag.RoomNumber)*@
                @Html.DropDownList("RoomNumber", null, "Select Room Number", htmlAttributes: new { @class = "form-control", @onchange = "this.form.submit();" })
                @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BedNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BedNumber", null, "Select Bed", htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.BedNumber, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.BedNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.6.3.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PainGuest/PainGuest/Views/GuestDetails/PrintAdvanceRecept.cshtml
@model PainGuest.Models.AdvanceReciptView
<div class="container">
    <div class="row">
        <div>
            <div class="h3"> Adnvace Amount Reciept</div>
            <table class="table">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.GuestName)</th>
                        <th>@Html.DisplayNameFor(model => model.AdvanceAmount)</th>
                        <th> Date </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Html.DisplayFor(model => model.GuestName)</td>
                        <td>@Html.DisplayFor(model => model.AdvanceAmount)</td>
                        <td> Date </td>
                        @*<td>
                                <input type="button" value="Go Somewhere Else" onclick="location.href='<%: Url.Action(" PrintSavePDF", "GuestDetails" , new { id=item.id }) %>'" />
                            </td>*@
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@